### ISSUE TITLE
Cannot detect the application type

### ISSUE THREAD

**Issue by GlauberF** [stevermeister/AngularPro-Screencast#84]
When running the build, I get the error Cannot detect the application type.
And I didn't change anything in your code, I just ran npm install and npm run build.

```
⠹ Generating browser application bundles (phase: building)...(node:8079) UnhandledPromiseRejectionWarning: Error: Cannot detect the application type
    at exports.parseRoutes (/var/www/html/guess-angular/node_modules/guess-parser/dist/guess-parser/index.js:827:15)
    at Object.routeProvider (/var/www/html/guess-angular/extend.webpack.config.js:13:16)
    at extractRoutes (/var/www/html/guess-angular/node_modules/guess-webpack/dist/guess-webpack/main.js:456:39)
    at GuessPlugin._execute (/var/www/html/guess-angular/node_modules/guess-webpack/dist/guess-webpack/main.js:489:9)
    at /var/www/html/guess-angular/node_modules/guess-webpack/dist/guess-webpack/main.js:485:54
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/guess-angular/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/guess-angular/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/var/www/html/guess-angular/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/var/www/html/guess-angular/node_modules/webpack/lib/Compiler.js:278:9)
    at /var/www/html/guess-angular/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/guess-angular/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/guess-angular/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /var/www/html/guess-angular/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/guess-angular/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/guess-angular/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /var/www/html/guess-angular/node_modules/webpack/lib/Compilation.js:1423:35
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by stevermeister** [comment]
Hi @GlauberF 
which one did you try to run? repository has a lot of examples
